"""Infrastructure verification test for property-based testing.

This module contains a simple test to verify that the Hypothesis
property testing infrastructure is properly configured.
"""

from hypothesis import given
from hypothesis import strategies as st


@given(st.integers())
def test_hypothesis_infrastructure(x: int) -> None:
    """Verify that Hypothesis property testing infrastructure works.

    This is a simple sanity check to ensure Hypothesis is properly
    configured and can generate test cases.

    Args:
        x: An arbitrary integer generated by Hypothesis.
    """
    # Simple property: adding zero to any integer returns the same integer
    assert x + 0 == x
